<a href="https://colab.research.google.com/github/sac-1999/pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if (torch.cuda.is_available()):
    print("cuda is enabled")
else:
    print("enable gpu, till we will use cpu")

cuda is enabled


In [3]:
#empty
torch.manual_seed(42)
a = torch.empty(2,3)
print(torch.zeros(2,3))
print(torch.ones(2,3))
print(torch.rand(2,3))
print(torch.tensor([[1,2,3], [3,4,5]]))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[1, 2, 3],
        [3, 4, 5]])


In [4]:
print(torch.arange(0,10,2))
print(torch.linspace(0,10, 8))
print(torch.eye(3))
print(torch.full((3,3), 5))
print(torch.full((3,3), 5).shape)

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.4286,  2.8571,  4.2857,  5.7143,  7.1429,  8.5714, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
torch.Size([3, 3])


In [5]:
a = torch.tensor([[1,2,3],[4,5,6]])
print(torch.empty_like(a))
print(torch.ones_like(a))
print(torch.zeros_like(a))
print(torch.rand_like(a, dtype = torch.float16))

tensor([[7310315409582465637, 2318265727211105906, 7957695011165139746],
        [3544393809949375010, 3976740237704573026, 7221857577833017655]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0.8418, 0.5098, 0.7998],
        [0.0591, 0.2275, 0.6045]], dtype=torch.float16)


In [6]:
print(a.dtype)
print(torch.tensor([1.0, 2.0, 3.0], dtype = torch.float64))
print(a.to(torch.float32))

torch.int64
tensor([1., 2., 3.], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [7]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a/2)
print(a**2)
print(a%2)
print(a//2)

tensor([[3, 4, 5],
        [6, 7, 8]])
tensor([[-1,  0,  1],
        [ 2,  3,  4]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[1, 0, 1],
        [0, 1, 0]])
tensor([[0, 1, 1],
        [2, 2, 3]])


In [8]:
b = a + 2

In [9]:
print(b)

tensor([[3, 4, 5],
        [6, 7, 8]])


In [10]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

tensor([[ 4,  6,  8],
        [10, 12, 14]])
tensor([[-2, -2, -2],
        [-2, -2, -2]])
tensor([[ 3,  8, 15],
        [24, 35, 48]])
tensor([[0.3333, 0.5000, 0.6000],
        [0.6667, 0.7143, 0.7500]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [11]:
a = torch.tensor([1.2, 2.3, 3.7])
print(torch.round(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, min = 2, max = 2))


tensor([1., 2., 4.])
tensor([2., 3., 4.])
tensor([1., 2., 3.])
tensor([2., 2., 2.])


In [12]:
a = torch.tensor([[1, 2, 3], [4,5,6]], dtype = torch.float)
print(torch.sum(a, dim = 0))
print(torch.mean(a))
print(torch.mean(a, dim = 0))
print(torch.median(a))
print(torch.min(a))
print(torch.max(a))
print(torch.prod(a))
print(torch.std(a))
print(torch.var(a))

tensor([5., 7., 9.])
tensor(3.5000)
tensor([2.5000, 3.5000, 4.5000])
tensor(3.)
tensor(1.)
tensor(6.)
tensor(720.)
tensor(1.8708)
tensor(3.5000)


In [13]:
print(torch.argmax(a))
print(torch.argmin(a))

tensor(5)
tensor(0)


In [14]:
print(torch.matmul(a,a.T))
c = torch.Tensor([1,2,3])
print(torch.dot(c,c))
print(torch.transpose(a,0, 1))

tensor([[14., 32.],
        [32., 77.]])
tensor(14.)
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [15]:
a = torch.rand((3,3))
print(torch.det(a))

tensor(-0.0596)


In [16]:
a = torch.randint(size=(2,3), high = 5, low = 1,)
b = torch.randint(size=(2,3), high = 5, low = 1,)
print(a)
print(b)
print(a >= b)
print(a <= b)
print(a == b)
print(torch.log(a))
print(torch.exp(a))
print(torch.sqrt(a))

tensor([[1, 2, 4],
        [4, 2, 2]])
tensor([[2, 4, 4],
        [1, 1, 4]])
tensor([[False, False,  True],
        [ True,  True, False]])
tensor([[ True,  True,  True],
        [False, False,  True]])
tensor([[False, False,  True],
        [False, False, False]])
tensor([[0.0000, 0.6931, 1.3863],
        [1.3863, 0.6931, 0.6931]])
tensor([[ 2.7183,  7.3891, 54.5981],
        [54.5981,  7.3891,  7.3891]])
tensor([[1.0000, 1.4142, 2.0000],
        [2.0000, 1.4142, 1.4142]])


In [17]:
##inplace operations to avoid memory usage
a.add_(b)
a.relu_()

tensor([[3, 6, 8],
        [5, 3, 6]])

In [18]:
##tensor copy
c = a
print(id(a))
print(id(c))
c = a.clone()
print(id(c))

134839056039856
134839056039856
134839056037264


In [32]:
#operations in in gpu
device = torch.device('cuda')
a = torch.rand(2,3, device = device)
b = torch.ones_like(a, device = 'cpu')
print(b.device)
b = b.to(device)
print(b.device)

cpu
cuda:0


In [40]:
# comparison of cpu vs gpu
#cpu time
from time import time
starttime = time()
a = torch.rand(10000, 10000)
b = a.clone()
c = torch.matmul(a,b)
print("CPU time taken  : " , time() - starttime)

##gpu time
starttime = time()
a = a.to(device)
b = b.to(device)
c = torch.matmul(a,b)
print("GPU time taken : ", time() - starttime)


CPU time taken  :  30.388569355010986
GPU time taken :  0.3167908191680908


In [58]:
#Reshaping
torch.manual_seed(42)
a = torch.randint(size = (2,3,2), low = 1, high = 10)
print(a)
# print(a.reshape(12,1))
print(a.reshape(1,12))
print(a.flatten())
print(a.permute(2,0,1))


tensor([[[7, 6],
         [8, 5],
         [1, 3]],

        [[8, 6],
         [5, 3],
         [5, 5]]])
tensor([[7, 6, 8, 5, 1, 3, 8, 6, 5, 3, 5, 5]])
tensor([7, 6, 8, 5, 1, 3, 8, 6, 5, 3, 5, 5])
tensor([[[7, 8, 1],
         [8, 5, 5]],

        [[6, 5, 3],
         [6, 3, 5]]])


In [68]:
a = torch.rand((226,226,3))
print(a.unsqueeze(0).shape)
print(a.shape)
c = a.unsqueeze(0)
print(c.shape)
print(c.squeeze(0).shape)

torch.Size([1, 226, 226, 3])
torch.Size([226, 226, 3])
torch.Size([1, 226, 226, 3])
torch.Size([226, 226, 3])


In [70]:
print(a.numpy())
c = a.numpy()
print(torch.from_numpy(c))

[[[0.5813674  0.18492013 0.19000751]
  [0.08957374 0.8888592  0.37091398]
  [0.28808767 0.06543833 0.51536196]
  ...
  [0.1401093  0.02303553 0.03098691]
  [0.28819126 0.56067234 0.99855006]
  [0.4074973  0.61677235 0.6790549 ]]

 [[0.7785705  0.05709147 0.70908386]
  [0.98007345 0.47566986 0.07013547]
  [0.78870463 0.27941352 0.19361776]
  ...
  [0.5695672  0.80530334 0.34934866]
  [0.9673664  0.14841902 0.39370203]
  [0.96236074 0.7529738  0.39960098]]

 [[0.7710647  0.6123576  0.6120187 ]
  [0.8016861  0.18903524 0.3513652 ]
  [0.05541122 0.7249629  0.17707205]
  ...
  [0.4523055  0.60575235 0.9640171 ]
  [0.6259485  0.28800404 0.4053204 ]
  [0.5568275  0.6217334  0.06927431]]

 ...

 [[0.13565451 0.9718838  0.32212567]
  [0.23617738 0.31000334 0.28285962]
  [0.93764377 0.93245727 0.79167956]
  ...
  [0.94019634 0.34312683 0.24597281]
  [0.05999476 0.6251118  0.12567759]
  [0.53130686 0.16922295 0.8730655 ]]

 [[0.41502273 0.71431464 0.80941087]
  [0.84616846 0.770316   0.5347578 ]
